### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by phaistonian** [nfarina/feeds#15]
Though the title does it, any plans on supporting it anytime soon?

**Comment by iansinnott** [comment]
:+1: for dark mode support

**Comment by kyranjamie** [comment]
Dark mode support would be great!

**Comment by joshdick** [comment]
Unread icons aren't displaying for me in dark mode in 10.10.3.

**Comment by unglud** [comment]
Dark mode please

![dark](https://up.kibakoapp.com/Y5bLVCaLvK!)

**Comment by nfarina** [comment]
Hey guys, I finally (sorry) got in and made some fixes for Dark Mode in PR #25. Anyone want to give it a spin before merging?
