### ISSUE TITLE
Articles in some feeds repeatedly appearing as new

### ISSUE THREAD

**Issue by ricog** [nfarina/feeds#23]
Occasionally (every several hours) it seems that one or two of my feeds will notify me of a new article when in fact the article was already retrieved. It seems to only be 1 article per feed.

The issue is also reported on the UserVoice site here: http://feedsapp.uservoice.com/forums/135330-community-support/suggestions/4525556-it-repeats-the-alerts

**Comment by ricog** [comment]
After closely watching this yesterday, it seems to only be a single article from a single feed. It would show up as new roughly every hour, which I'm guessing is the check interval for an RSS/Atom feed. I disabled the feed and didn't have any more trouble.

I re-enabled the feed today and immediately got a notification on the same article. I will watch to see if notifications repeat.

**Comment by ricog** [comment]
I finally just disabled the trouble feed.

**Comment by nfarina** [comment]
Let me know if this crops up again!
